"""m

Revision ID: 09e6a2ee7aa3
Revises: 46a64d1aac0f
Create Date: 2025-04-06 16:54:00.395792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09e6a2ee7aa3'
down_revision: Union[str, None] = '46a64d1aac0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_client_appointerId_user', 'client', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_client_appointerId_user', 'client', 'user', ['appointerId'], ['id'])
    # ### end Alembic commands ###
