"""m

Revision ID: 338676e9522a
Revises: 77d341204f73
Create Date: 2025-04-09 18:10:51.506377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '338676e9522a'
down_revision: Union[str, None] = '77d341204f73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('info', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('department', 'info')
    # ### end Alembic commands ###
