"""m

Revision ID: 47a08e350f94
Revises: db855ef18402
Create Date: 2025-04-07 09:09:13.873301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47a08e350f94'
down_revision: Union[str, None] = 'db855ef18402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('contractNo', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'contractNo')
    # ### end Alembic commands ###
