"""m

Revision ID: 6203415ac0d5
Revises: 6befd72a98fb
Create Date: 2025-04-03 18:50:14.114119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6203415ac0d5'
down_revision: Union[str, None] = '6befd72a98fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('fromSource', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('IDNumber', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('weixin', sa.Text(), nullable=True),
    sa.Column('QQ', sa.Text(), nullable=True),
    sa.Column('douyin', sa.Text(), nullable=True),
    sa.Column('rednote', sa.Text(), nullable=True),
    sa.Column('shangwutong', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('clientStatus', sa.Integer(), nullable=True),
    sa.Column('affiliatedUserId', sa.Integer(), nullable=True),
    sa.Column('createdUserId', sa.Integer(), nullable=True),
    sa.Column('createdTime', sa.DateTime(), nullable=True),
    sa.Column('info', sa.Text(), nullable=True),
    sa.Column('detailedInfo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['affiliatedUserId'], ['user.id'], name=op.f('fk_client_affiliatedUserId_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client')
    # ### end Alembic commands ###
