"""m

Revision ID: 6befd72a98fb
Revises: 6a940763276b
Create Date: 2025-04-03 09:24:50.995960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6befd72a98fb'
down_revision: Union[str, None] = '6a940763276b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('vocation', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('status', sa.Integer(), nullable=True))
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', mysql.TEXT(), nullable=True))
    op.drop_column('user', 'status')
    op.drop_column('user', 'vocation')
    op.drop_column('user', 'address')
    # ### end Alembic commands ###
