"""m

Revision ID: 735e5a9d87a6
Revises: 47a08e350f94
Create Date: 2025-04-07 22:56:14.280833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '735e5a9d87a6'
down_revision: Union[str, None] = '47a08e350f94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clientId', sa.Integer(), nullable=True),
    sa.Column('teacherId', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('paymentMethod', sa.Integer(), nullable=True),
    sa.Column('info', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['clientId'], ['client.id'], name=op.f('fk_payment_clientId_client')),
    sa.ForeignKeyConstraint(['teacherId'], ['user.id'], name=op.f('fk_payment_teacherId_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    # ### end Alembic commands ###
