"""m

Revision ID: 77d341204f73
Revises: 85b5a25a6d80
Create Date: 2025-04-09 17:13:47.148692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '77d341204f73'
down_revision: Union[str, None] = '85b5a25a6d80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('creatorId', sa.Integer(), nullable=True))
    op.drop_column('client', 'createdUserId')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('createdUserId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('client', 'creatorId')
    # ### end Alembic commands ###
