"""m

Revision ID: a2fe4d358e62
Revises: 09e6a2ee7aa3
Create Date: 2025-04-06 17:17:44.583424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2fe4d358e62'
down_revision: Union[str, None] = '09e6a2ee7aa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('info', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_school'))
    )
    op.drop_index('fk_client_appointerId_user', table_name='client')
    op.add_column('course', sa.Column('schoolId', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_course_schoolId_school'), 'course', 'school', ['schoolId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_course_schoolId_school'), 'course', type_='foreignkey')
    op.drop_column('course', 'schoolId')
    op.create_index('fk_client_appointerId_user', 'client', ['appointerId'], unique=False)
    op.drop_table('school')
    # ### end Alembic commands ###
