"""m

Revision ID: a683c5a62f65
Revises: 338676e9522a
Create Date: 2025-04-09 18:54:09.060763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a683c5a62f65'
down_revision: Union[str, None] = '338676e9522a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school', sa.Column('address', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school', 'address')
    # ### end Alembic commands ###
