"""m

Revision ID: b17aa071ac5a
Revises: b430eb6245f1
Create Date: 2025-04-04 16:39:45.360376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b17aa071ac5a'
down_revision: Union[str, None] = 'b430eb6245f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_client_createdUserId_user', 'client', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_client_createdUserId_user', 'client', 'user', ['createdUserId'], ['id'])
    # ### end Alembic commands ###
