"""m

Revision ID: b430eb6245f1
Revises: 6203415ac0d5
Create Date: 2025-04-04 16:32:12.183929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b430eb6245f1'
down_revision: Union[str, None] = '6203415ac0d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_client_createdUserId_user'), 'client', 'user', ['createdUserId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_client_createdUserId_user'), 'client', type_='foreignkey')
    # ### end Alembic commands ###
