"""m

Revision ID: d17a694a0057
Revises: a2fe4d358e62
Create Date: 2025-04-06 17:27:05.416931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd17a694a0057'
down_revision: Union[str, None] = 'a2fe4d358e62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('appointDate', sa.Date(), nullable=True))
    op.drop_column('client', 'appointTime')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('appointTime', mysql.DATETIME(), nullable=True))
    op.drop_column('client', 'appointDate')
    # ### end Alembic commands ###
