"""m

Revision ID: d56fc3f365b2
Revises: b17aa071ac5a
Create Date: 2025-04-06 16:44:23.019391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd56fc3f365b2'
down_revision: Union[str, None] = 'b17aa071ac5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('creatorId', sa.Integer(), nullable=True),
    sa.Column('createdTime', sa.DateTime(), nullable=True),
    sa.Column('info', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['creatorId'], ['user.id'], name=op.f('fk_course_creatorId_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course'))
    )
    op.add_column('client', sa.Column('appointerId', sa.Integer(), nullable=True))
    op.add_column('client', sa.Column('courseIds', sa.JSON(), nullable=True))
    op.add_column('client', sa.Column('processStatus', sa.Integer(), nullable=True))
    op.add_column('client', sa.Column('appointTime', sa.DateTime(), nullable=True))
    op.add_column('client', sa.Column('cooperateTime', sa.DateTime(), nullable=True))
    op.drop_index('fk_client_createdUserId_user', table_name='client')
    op.create_foreign_key(op.f('fk_client_appointerId_user'), 'client', 'user', ['appointerId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_client_appointerId_user'), 'client', type_='foreignkey')
    op.create_index('fk_client_createdUserId_user', 'client', ['createdUserId'], unique=False)
    op.drop_column('client', 'cooperateTime')
    op.drop_column('client', 'appointTime')
    op.drop_column('client', 'processStatus')
    op.drop_column('client', 'courseIds')
    op.drop_column('client', 'appointerId')
    op.drop_table('course')
    # ### end Alembic commands ###
