"""m

Revision ID: db855ef18402
Revises: 9361e6169cee
Create Date: 2025-04-06 17:40:55.083240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db855ef18402'
down_revision: Union[str, None] = '9361e6169cee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('schoolId', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_user_schoolId_school'), 'user', 'school', ['schoolId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_schoolId_school'), 'user', type_='foreignkey')
    op.drop_column('user', 'schoolId')
    # ### end Alembic commands ###
