"""m

Revision ID: e5963ee76ac1
Revises: a683c5a62f65
Create Date: 2025-04-10 10:25:00.900608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e5963ee76ac1'
down_revision: Union[str, None] = 'a683c5a62f65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('duration', sa.Float(), nullable=True))
    op.add_column('course', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('course', sa.Column('chiefTeacherId', sa.Integer(), nullable=True))
    op.add_column('course', sa.Column('classTeacherId', sa.Integer(), nullable=True))
    op.add_column('course', sa.Column('teachingAssistantId', sa.Integer(), nullable=True))
    op.alter_column('course', 'category',
               existing_type=mysql.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course', 'category',
               existing_type=sa.Integer(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.drop_column('course', 'teachingAssistantId')
    op.drop_column('course', 'classTeacherId')
    op.drop_column('course', 'chiefTeacherId')
    op.drop_column('course', 'price')
    op.drop_column('course', 'duration')
    # ### end Alembic commands ###
